plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\agust\\Desktop\\10 SKILLS ADRI Y JUANPE\\10 SKILLS ADRI Y JUANPE\\kit-instagram-web"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/admin-data.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"