// ADMIN-DATA — gestionado desde el panel /admin.html
// No editar manualmente si usás el panel de administración
const ADMIN_DATA = {
  "lastUpdated": "2026-06-12T20:30:29.940Z",
  "igStats": {
    "posts": 84,
    "seguidores": 235,
    "siguiendo": 34
  },
  "matchResults": {},
  "scorersByMatch": {
    "amistoso": [
      "Elias x4",
      "Pata x1",
      "Mandinga x1"
    ],
    "f1": [
      "Seba T x1"
    ],
    "f2": [
      "Elias x1",
      "Seba T x1",
      "Sena x1"
    ],
    "f3": [
      "Mandinga x1"
    ],
    "f4": [
      "Elias x1"
    ],
    "f5": [
      "Elias x1",
      "Facu Munchs x1"
    ],
    "f6": [
      "Elias x3",
      "Mandinga x1",
      "Andres G x1",
      "Facu M x1",
      "Pato x1"
    ],
    "f7": [
      "Elias x1",
      "Mandinga x1",
      "Pata x1",
      "Sena x1",
      "Franco F x1",
      "Andres G x1"
    ],
    "f8": [
      "Elias x1",
      "Mandinga x1"
    ],
    "f9": [
      "Sena x1",
      "Diego x1"
    ]
  },
  "playerMinutes": {
    "amistoso": {
      "Jubin": 90,
      "Brandon": 55,
      "Renzo": 0,
      "Vidal": 70,
      "Franco F": 70,
      "Diego": 0,
      "Elias": 80,
      "Negrin": 45,
      "Nando": 90,
      "Lolo": 0,
      "Pata": 60,
      "Franco Irri": 65,
      "Facu Munchs": 0,
      "Seba B": 50,
      "Enzo": 0,
      "Pato": 90,
      "Seba T": 0,
      "Mati": 0,
      "Mandinga": 45,
      "Mariano": 0,
      "Fabian Couto": 90,
      "Sena": 90,
      "Ignacio Luy": 0,
      "Andres Guerra": 0,
      "Lucas Godoy": 0
    },
    "f1": {
      "Jubin": 90,
      "Vicente": 20,
      "Brandon": 60,
      "Juli Rios": 45,
      "Franco F": 90,
      "Diego": 30,
      "Negrin": 20,
      "Nando": 90,
      "Lolo": 55,
      "Pata": 0,
      "Franco Irri": 60,
      "Facu Munchs": 90,
      "Seba T": 90,
      "Mati": 70,
      "Sena": 75
    },
    "f2": {
      "Jubin": 90,
      "Brandon": 35,
      "Vidal": 45,
      "Franco F": 90,
      "Diego": 0,
      "Elias": 90,
      "Nando": 90,
      "Franco Irri": 45,
      "Facu Munchs": 25,
      "Seba B": 40,
      "Enzo": 60,
      "Pato": 90,
      "Seba T": 65,
      "Mati": 90,
      "Mandinga": 30,
      "Fabian Couto": 0,
      "Sena": 55
    },
    "f3": {
      "Jubin": 90,
      "Vicente": 45,
      "Juli Rios": 90,
      "Vidal": 45,
      "Franco F": 90,
      "Diego": 15,
      "Elias": 40,
      "Negrin": 10,
      "Nando": 0,
      "Lolo": 15,
      "Pata": 75,
      "Franco Irri": 45,
      "Seba B": 45,
      "Pato": 90,
      "Seba T": 35,
      "Mati": 90,
      "Mandinga": 50,
      "Mariano": 10,
      "Sena": 80,
      "Ignacio Luy": 30
    },
    "f4": {
      "Jubin": 90,
      "Brandon": 20,
      "Juli Rios": 60,
      "Vidal": 45,
      "Franco F": 90,
      "Diego": 0,
      "Elias": 90,
      "Nando": 25,
      "Lolo": 0,
      "Franco Irri": 60,
      "Seba B": 90,
      "Enzo": 30,
      "Pato": 90,
      "Mati": 65,
      "Mandinga": 25,
      "Mariano": 0,
      "Sena": 70,
      "Ignacio Luy": 30
    },
    "f5": {
      "Jubin": 90,
      "Vicente": 45,
      "Brandon": 45,
      "Juli Rios": 0,
      "Franco F": 60,
      "Diego": 15,
      "Elias": 75,
      "Negrin": 0,
      "Lolo": 45,
      "Franco Irri": 45,
      "Facu Munchs": 45,
      "Seba B": 45,
      "Enzo": 90,
      "Pato": 90,
      "Mati": 90,
      "Mandinga": 65,
      "Mariano": 0,
      "Sena": 45,
      "Ignacio Luy": 45,
      "Andres Guerra": 0
    },
    "f6": {
      "Jubin": 90,
      "Vicente": 90,
      "Brandon": 90,
      "Elias": 55,
      "Negrin": 15,
      "Lolo": 20,
      "Franco Irri": 75,
      "Facu Munchs": 45,
      "Enzo": 90,
      "Pato": 80,
      "Mati": 70,
      "Mandinga": 60,
      "Sena": 90,
      "Ignacio Luy": 60,
      "Andres Guerra": 30,
      "Lucas Godoy": 30
    },
    "f7": {
      "Jubin": 90,
      "Brandon": 80,
      "Juli Rios": 90,
      "Vidal": 50,
      "Franco F": 0,
      "Diego": 25,
      "Elias": 90,
      "Lolo": 30,
      "Pata": 60,
      "Franco Irri": 40,
      "Facu Munchs": 15,
      "Pato": 90,
      "Mandinga": 65,
      "Sena": 55,
      "Andres Guerra": 30,
      "Lucas Godoy": 45
    },
    "f8": {
      "Jubin": 90,
      "Vicente": 30,
      "Brandon": 45,
      "Juli Rios": 90,
      "Vidal": 60,
      "Franco F": 75,
      "Diego": 0,
      "Elias": 60,
      "Negrin": 15,
      "Nando": 15,
      "Pata": 45,
      "Seba B": 45,
      "Enzo": 45,
      "Pato": 45,
      "Mati": 60,
      "Mandinga": 75,
      "Sena": 90,
      "Ignacio Luy": 30,
      "Lucas Godoy": 45
    },
    "f9": {
      "Jubin": 90,
      "Vicente": 70,
      "Brandon": 90,
      "Juli Rios": 0,
      "Franco F": 90,
      "Diego": 20,
      "Elias": 90,
      "Negrin": 25,
      "Nando": 75,
      "Pata": 90,
      "Enzo": 0,
      "Pato": 0,
      "Mati": 90,
      "Mandinga": 90,
      "Sena": 90,
      "Lucas Godoy": 65
    }
  }
};
